apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilicum
      version: 1.10.5
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: cilium-system
  interval: 10m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml
  values: {}