apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
  - manifests/namespace.yaml
  - manifests/config.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
