apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: ingress
  annotations:
    # Grant it an IP on the network
    metallb.universe.tf/address-pool: lan-address-pool
  labels:
    app: envoy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: envoy
