apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: envoy
  annotations:
    # Grant it an IP on the network
    metallb.universe.tf/address-pool: lan-address-pool
  labels:
    app: envoy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
  selector:
    app: envoy
